spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ewqDSA19@&
    url: jdbc:mysql://localhost:3306/msa_practice


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

server:
  port: 19000




