spring:
  application:
    name: product-service
  profiles:
    active: local
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

server:
  port: 1234


# 수동으로 config 정보 update
# url path: /actuator/refresh
management:
  endpoints:
    web:
      exposure:
        include: refresh
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"