spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa_practice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ewqdsa1927
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: