spring:
  application:
    name: server

server:
  port: 19090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    hostname: localhost

  server:
    evictableCacheSize: 1000  # 캐시 크기 조정



logging:
  level:
    com.netflix.eureka: WARN  # WARN 이상의 로그만 출력
