spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa_exam
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: