server:
  port: 1234

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  profiles:
    active: local
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

jwt:
  secretKey: bXlmaXJzdG1zYXByYWN0aWNlcHJvamVjdHN1Y2Vzc2Z1bGluZ3JlbWluZWdvam9zYXRvcnVzdW1tb25lcnN3YXJmdW5ueWdhbWVnb2RnYW1l

management:
  endpoints:
    web:
      exposure:
        include: refresh