server:
  port: 19095

spring:
  application:
    name: auth-service
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka
  instance:
   hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: prometheus, refresh
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  level:
    org.hibernate.SQL: DEBUG

jwt:
  secretKey: bXlmaXJzdG1zYXByYWN0aWNlcHJvamVjdHN1Y2Vzc2Z1bGluZ3JlbWluZWdvam9zYXRvcnVzdW1tb25lcnN3YXJmdW5ueWdhbWVnb2RnYW1l
  issuer: auth-service
  expiration: 3600_000
admin:
  code: adadadmin

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 20s


# Config-Sever 구성시 사용
#spring:
#  profiles:
#    active: local
#  config:
#    import: "configserver:"
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server

